---
fixtures:
  repositories:
    haveged: https://github.com/simp/pupmod-simp-haveged
    firewalld:
      repo: https://github.com/simp/pupmod-voxpupuli-firewalld
      ref: v4.1.0
    iptables: https://github.com/simp/pupmod-simp-iptables
    selinux: https://github.com/simp/pupmod-simp-selinux
    simp_options: https://github.com/simp/pupmod-simp-simp_options
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    vox_selinux:
      repo: https://github.com/simp/pupmod-voxpupuli-selinux
      branch: simp-master
  symlinks:
    krb5: "#{source_dir}"
