---
fixtures:
  repositories:
    augeas_core: https://github.com/simp/pupmod-puppetlabs-augeas_core.git
    haveged: https://github.com/simp/pupmod-simp-haveged.git
    firewalld: https://github.com/simp/pupmod-voxpupuli-firewalld.git
    iptables: https://github.com/simp/pupmod-simp-iptables.git
    selinux: https://github.com/simp/pupmod-simp-selinux.git
    selinux_core: https://github.com/simp/pupmod-puppetlabs-selinux_core.git
    simp_firewalld: https://github.com/simp/pupmod-simp-simp_firewalld.git
    simp_options: https://github.com/simp/pupmod-simp-simp_options.git
    simplib: https://github.com/simp/pupmod-simp-simplib.git
    stdlib: https://github.com/simp/puppetlabs-stdlib.git
    systemd: https://github.com/simp/puppet-systemd.git
    vox_selinux:
      repo: https://github.com/simp/pupmod-voxpupuli-selinux.git
      branch: simp-master
  symlinks:
    krb5: "#{source_dir}"
