---
fixtures:
  repositories:
    haveged: https://github.com/simp/pupmod-simp-haveged
    firewalld: https://github.com/simp/pupmod-voxpupuli-firewalld
    iptables: https://github.com/simp/pupmod-simp-iptables
    selinux: https://github.com/simp/pupmod-simp-selinux
    selinux_core:
      repo: https://github.com/simp/pupmod-puppetlabs-selinux_core.git
      puppet_version: ">= 6.0.0"
    simp_options: https://github.com/simp/pupmod-simp-simp_options
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    systemd: https://github.com/simp/puppet-systemd
    vox_selinux:
      repo: https://github.com/simp/pupmod-voxpupuli-selinux
      branch: simp-master
  symlinks:
    krb5: "#{source_dir}"
